# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    #customer.speaker.name: 'azertyuio'
    #customer.speaker.lastName: 'cvbn,'

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    customer.name_registry:
        class: CustomerBundle\Service\NameRegistry


    customer.speaker:
        class: CustomerBundle\Service\Speaker
        arguments: ['@customer.name_registry']

    customer.notifier:
        class: CustomerBundle\Service\Notifier
        arguments:
            - '@twig'
            - '@mailer'
            - '%recipient%'




