customer_homepage:
    path:     /
    defaults:
        _controller: CustomerBundle:Default:index




customer_contact:
    path:    /contact
    defaults: 
        _controller: CustomerBundle:Page:contact



customer:
    resource: routing/customer.yml
    prefix:    /customer
