foo_homepage:
    path:     /
    defaults: { _controller: FooBundle:Default:index }

foo_:
    path:    /foo
    defaults:
        _controller: FooBundle:Default:foo
##  -->FooBundle-->Controller-->DefaultController.php --> public function fooAction  ##

bar_:
    path:    /bar
    defaults: 
        _controller: FooBundle:Default:bar

test:
    resource: routing/test.yml
    prefix: /test





