foo_homepage:
    path:     /
    defaults: { _controller: FooBundle:Default:index }

foo_:
    path:    /foo
    defaults:
        _controller: FooBundle:Default:foo
##  -->FooBundle-->Controller-->DefaultController.php --> public function fooAction  ##

bar_:
    path:    /bar
    defaults: 
        _controller: FooBundle:Default:bar

##  plusieur route on le meme prefix donc on les met dans un autre dossier et on specifie le chemin avec resource et le prefix en question  ##
test:
    resource: routing/test.yml
    prefix: /test





