foo_homepage:
    path:     /
    defaults: { _controller: FooBundle:Default:index }

foo_:
    path:    /foo
    defaults:
        _controller: FooBundle:Default:foo
##  -->FooBundle-->Controller-->DefaultController.php --> public function fooAction  ##

bar_:
    path:    /bar
    defaults: 
        _controller: FooBundle:Default:bar

##  On passe le number_action au dessus de test_param sinon test_param prend le number en parametre  ## 
number_action:
    path:    /{number}
    defaults:
        _controller: FooBundle:Default:number
    requirements:
        number: \d+



test_param:
    path:    /{test_param}
    defaults:
        _controller: FooBundle:Default:testParam 



